### ISSUE TITLE
[Question] Is there a way to change the language when the device language changes?

### ISSUE THREAD

**Issue by InquisitorJax** [maxkoshevoi/XCTLocalizationDemo#2]
Is it possible, while the app is open, to detect a platform device language change?

For me that's the only part missing from this great demo ;)

**Comment by maxkoshevoi** [comment]
Great question! I did some investigation and discovered two things:
1) `App.OnStart` is called when devise's language is changed
2) There is no cross-platform way to get current language of the device (`CultureInfo.CurrentCulture` won't be updated with new device language)

Created a PR in XCT to add such API: https://github.com/xamarin/XamarinCommunityToolkit/pull/1200

After it's added, you would be able to do something like this:

```cs
protected override void OnStart()
{
    LocalizationResourceManager.Current.CurrentCulture = DeviceInfo.CurrentCulture;
}
```

**Comment by InquisitorJax** [comment]
Just to flesh this out a bit, it seems on iOS, one doesn't have to worry about this so much, as it seems the app restarts when device language is changed, so you can hook into the AppStart as mentioned.

For Android, you can add a broadcast receiver, and change locale when that gets triggered:
So in MainActivity, do this:
	private void RegisterLocaleBroadcastReceiver()
		{
			var receiver = new LocaleBroadcastReceiver();
			IntentFilter filter = new IntentFilter(Intent.ActionLocaleChanged);
			RegisterReceiver(receiver, filter);
		}
... and in the receiver, you can get the new CultureInfo like:
var newCultureInfo = new CultureInfo(Locale.Default.Language);
and do whatever you need to with that from there.

We don't have manual language selection, so we just set the CurrentThread.CurrentCulture & CurrentUICulture

**Comment by maxkoshevoi** [comment]
> on iOS, one doesn't have to worry about this so much, as it seems the app restarts when device language is changed

True, but why does iOS have [device language changed event](docs.microsoft.com/en-us/dotnet/api/foundation.nslocale.notifications.observecurrentlocaledidchange)? Did you test that `CultureInfo.CurrentCulture` is changed in iOS app when device language is changed?

> For Android, you can add a broadcast receiver, and change locale when that gets triggered

As for Android, app also gets restarted (it looks like activity is restarted, not the whole app), but `CultureInfo.CurrentCulture` doesn't change.

To add to your solution, you can also register receiver by creating new class like this:
```cs
[BroadcastReceiver(Enabled = true)]
[IntentFilter(new[] { Intent.ActionLocaleChanged })]
public class LocaleChangeReceiver : BroadcastReceiver
{
    public override void OnReceive(Context context, Intent intent)
    {
        // Save new culture somewhere
        CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo(Locale.Default.Language);

        // Check that app's language is set to "system" (if app has manual language selection)
        // This check example of a custom check. Classes SettingsRepository and AppLanguage don't exist in XF or XCT
        if (SettingsRepository.Settings.Language == AppLanguage.FollowSystem)
        {
            // Update app's localization language
            LocalizationResourceManager.Current.CurrentCulture = CultureInfo.CurrentCulture;
        }
    }
}
```
